Include missing string header
Fixes the following compiler error:

  In file included from ../builtins.cc:19:
  ../builtins.hh:103:21: error: field ‘name’ has incomplete type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’}
    103 |         std::string name;
        |                     ^~~~

Signed-off-by: Gabriel F. T. Gomes <gagomes@suse.de>